### ISSUE TITLE
Could you please provide squad_train.csv and squad_test.csv ?

### ISSUE THREAD

**Issue by lili1234567890** [gsasikiran/automatic-question-generation#15]

**Comment by desinurch** [comment]
Hi, i've removed some data for storage so maybe you could try with these
[squad_train.csv](https://drive.google.com/file/d/1he4ThLSxhdnYk3dLzqVrKMSdZaLM7heR/view?usp=sharing)
[squad_dev.csv](https://drive.google.com/file/d/15ukJW0nh3iTBxp41c6Ho-2gqfWuBYTj3/view?usp=sharing)

**Comment by lili1234567890** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，邮件我已收到，祝好！

**Comment by lili1234567890** [comment]
hi， thank you give me some files, but i still lack some files. such fields = [('context', TEXT), ('question', TEXT), ('bio', BIO), ('lex', LEX)]; Could you please provide some files in the storage? If not, can you provide a demo of these files?

**Comment by desinurch** [comment]
> hi， thank you give me some files, but i still lack some files. such fields = [('context', TEXT), ('question', TEXT), ('bio', BIO), ('lex', LEX)]; Could you please provide some files in the storage? If not, can you provide a demo of these files?

are you referring to file [train.py](https://github.com/gsasikiran/automatic-question-generation/blob/master/main/train.py) line 61? if yes, torchtext has updated their code, so now you should change `from torchtext import data` -> `from torchtext.legacy import data`

**Comment by lili1234567890** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，邮件我已收到，祝好！
